{
  "name": "<%= it.appName %>",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "description": "Application Nodefony — générée par `nodefony create app`",
  "main": "dist/index.js",
  "engines": {
    "node": ">=24.0.0"
  },
  "scripts": {
    "prepare": "node --eval \"const f=require('node:fs');if(f.existsSync('.githooks'))try{require('node:child_process').execSync('git config core.hooksPath .githooks',{stdio:'ignore'})}catch{}\"",
    "dev": "nodefony development",
    "build": "rolldown -c rolldown.config.ts<% if (it.front) { %> && nodefony frontend:build<% } %>",
    "start": "nodefony production",
    "stop": "nodefony stop",
    "status": "nodefony status",
    "test": "vitest run",
    "coverage:setup": "npm i -D @vitest/coverage-v8",
    "coverage": "vitest run --coverage",
    "test:e2e": "npm run build && vitest run -c vitest.e2e.config.ts",
    "typecheck": "tsgo --noEmit",
    "verify": "npm run typecheck && npm run lint && npm run format:check && npm test && npm run check",
    "check": "nodefony check",
    "inspect": "nodefony inspect",
    "ai:sync": "nodefony ai:sync",
    "see:setup": "npm i -D playwright axe-core",
    "see": "node node_modules/@nodefony/devkit/skills/nodefony-browser/scripts/inspect.mjs",
    "watch:screen": "node node_modules/@nodefony/devkit/skills/nodefony-browser/scripts/watch.mjs",
    "audit:setup": "npm i -D playwright lighthouse",
    "audit:web": "node node_modules/@nodefony/devkit/skills/nodefony-browser/scripts/audit.mjs",
    "clean": "node --eval \"require('node:fs').rmSync('dist',{recursive:true,force:true})\"",
    "lint": "oxlint --deny-warnings",
    "format": "prettier --write .",
    "format:check": "prettier --check ."<% if (it.complete) { %>,
    "infra:up": "docker compose up -d",
    "infra:down": "docker compose down"<% } %>
  },
  "dependencies": {
    "nodefony": "^<%= it.nodefonyVersion %>",
    "@nodefony/http": "^<%= it.nodefonyVersion %>",
    "@nodefony/framework": "^<%= it.nodefonyVersion %>",
<% if (it.complete) { %>    "@nodefony/orm-core": "^<%= it.nodefonyVersion %>",
    "@nodefony/drizzle": "^<%= it.nodefonyVersion %>",
    "drizzle-orm": "<%= it.pkg["drizzle-orm"] %>",
    "@nodefony/user": "^<%= it.nodefonyVersion %>",
    "@node-rs/argon2": "<%= it.pkg["@node-rs/argon2"] %>",
    "@nodefony/realtime": "^<%= it.nodefonyVersion %>",
    "@nodefony/security": "^<%= it.nodefonyVersion %>",
    "@nodefony/frontend": "^<%= it.nodefonyVersion %>",
    "@nodefony/studio": "^<%= it.nodefonyVersion %>",
    "@nodefony/redis": "^<%= it.nodefonyVersion %>",
<% } else if (it.front) { %>    "@nodefony/frontend": "^<%= it.nodefonyVersion %>",
<% } %><% if (it.front) { for (const [n, v] of Object.entries(it.front.deps)) { %>    "<%= n %>": "<%= v %>",
<% } } %>    "zod": "<%= it.pkg["zod"] %>"
  },
  "devDependencies": {
    "@nodefony/devkit": "^<%= it.nodefonyVersion %>",
    "@types/node": "<%= it.pkg["@types/node"] %>",
    "@typescript/native-preview": "<%= it.pkg["@typescript/native-preview"] %>",
    "oxlint": "<%= it.pkg["oxlint"] %>",
    "prettier": "<%= it.pkg["prettier"] %>",
    "rolldown": "<%= it.pkg["rolldown"] %>",
<% if (it.front) { for (const [n, v] of Object.entries(it.front.devDeps)) { %>    "<%= n %>": "<%= v %>",
<% } } %>    "typescript": "<%= it.pkg["typescript"] %>",
    "vitest": "<%= it.pkg["vitest"] %>"
  }
}
