{
  "name": "<%= it.appName %>",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "description": "Application Nodefony — générée par `nodefony create app`",
  "main": "dist/index.js",
  "scripts": {
    "dev": "nodefony development",
    "build": "rolldown -c rolldown.config.ts<% if (it.front) { %> && nodefony frontend:build<% } %>",
    "start": "nodefony production",
    "stop": "nodefony stop",
    "status": "nodefony status",
    "test": "vitest run",
    "test:e2e": "npm run build && vitest run -c vitest.e2e.config.ts",
    "typecheck": "tsgo --noEmit",
    "check": "nodefony check",
    "lint": "eslint .",
    "format": "prettier --write ."<% if (it.complete) { %>,
    "infra:up": "docker compose up -d",
    "infra:down": "docker compose down"<% } %>
  },
  "dependencies": {
    "nodefony": "^<%= it.nodefonyVersion %>",
    "@nodefony/http": "^<%= it.nodefonyVersion %>",
    "@nodefony/framework": "^<%= it.nodefonyVersion %>",
<% if (it.complete) { %>    "@nodefony/orm-core": "^<%= it.nodefonyVersion %>",
    "@nodefony/drizzle": "^<%= it.nodefonyVersion %>",
    "drizzle-orm": "<%= it.pkg["drizzle-orm"] %>",
    "@nodefony/user": "^<%= it.nodefonyVersion %>",
    "@nodefony/realtime": "^<%= it.nodefonyVersion %>",
    "@nodefony/security": "^<%= it.nodefonyVersion %>",
    "@nodefony/frontend": "^<%= it.nodefonyVersion %>",
    "@nodefony/studio": "^<%= it.nodefonyVersion %>",
    "@nodefony/redis": "^<%= it.nodefonyVersion %>",
<% } else if (it.front) { %>    "@nodefony/frontend": "^<%= it.nodefonyVersion %>",
<% } %><% if (it.front) { for (const [n, v] of Object.entries(it.front.deps)) { %>    "<%= n %>": "<%= v %>",
<% } } %>    "zod": "<%= it.pkg["zod"] %>"
  },
  "devDependencies": {
    "@types/node": "<%= it.pkg["@types/node"] %>",
    "@typescript-eslint/eslint-plugin": "<%= it.pkg["@typescript-eslint/eslint-plugin"] %>",
    "@typescript-eslint/parser": "<%= it.pkg["@typescript-eslint/parser"] %>",
    "@typescript/native-preview": "<%= it.pkg["@typescript/native-preview"] %>",
    "eslint": "<%= it.pkg["eslint"] %>",
    "eslint-config-prettier": "<%= it.pkg["eslint-config-prettier"] %>",
    "prettier": "<%= it.pkg["prettier"] %>",
    "rolldown": "<%= it.pkg["rolldown"] %>",
<% if (it.front) { for (const [n, v] of Object.entries(it.front.devDeps)) { %>    "<%= n %>": "<%= v %>",
<% } } %>    "typescript": "<%= it.pkg["typescript"] %>",
    "vitest": "<%= it.pkg["vitest"] %>"
  }
}
