{
  "name": "<%= it.appName %>",
  "version": "0.1.0",
  "private": true,
  "license": "<%= it.license %>",
  "type": "module",
  "description": "Application Nodefony — générée par `nodefony create app`",
  "main": "dist/index.js",
  "engines": {
    "node": ">=24.0.0"
  },
<% if (it.complete && it.dialect === "sqlite") { %>  "allowScripts": {
    "better-sqlite3": false
  },
<% } %>  "scripts": {
    "prepare": "node --eval \"const f=require('node:fs');if(f.existsSync('.githooks'))try{require('node:child_process').execSync('git config core.hooksPath .githooks',{stdio:'ignore'})}catch{}\"",
    "dev": "nodefony development",
    "build": "rolldown -c rolldown.config.ts<% if (it.front) { %> && nodefony frontend:build<% } %>",
    "start": "nodefony production",
    "stop": "nodefony stop",
    "status": "nodefony status",
    "test": "vitest run",
    "coverage": "vitest run --coverage",
    "test:e2e": "npm run build && vitest run -c vitest.e2e.config.ts",
    "typecheck": "tsgo --noEmit",
    "verify": "npm run typecheck && npm run lint && npm run format:check && npm test && npm run build && npm run doctor",
    "doctor": "nodefony doctor",
    "doctor:live": "nodefony doctor --live",
    "audit:deps": "npm audit --omit=dev",
    "licenses": "nodefony licenses",
    "licenses:write": "nodefony licenses --write",
    "inspect": "nodefony inspect",
    "ai:sync": "nodefony ai:sync",
    "see": "nodefony see",
    "clean": "node --eval \"require('node:fs').rmSync('dist',{recursive:true,force:true})\"",
    "lint": "oxlint --deny-warnings",
    "format": "prettier --write .",
    "format:check": "prettier --check ."<% if (it.complete) { %>,
    "infra:up": "docker compose up -d",
    "infra:down": "docker compose down"<% } %>
  },
  "nodefony": {
    "scripts": {
      "prepare": "Branche les hooks git du projet, s'il y en a. Lancé par npm à l'installation.",
      "dev": "Démarre l'application en développement (rechargement à chaud).",
      "build": "Compile l'application<% if (it.front) { %>, bundles frontend compris<% } %>.",
      "start": "Démarre l'application en production, au premier plan.",
      "stop": "Arrête proprement l'application qui tourne.",
      "status": "Dit si l'application tourne, et sur quels ports.",
      "test": "Lance les tests unitaires (aucun serveur requis).",
      "test:e2e": "Bâtit, démarre un vrai serveur, et éprouve les routes de bout en bout.",
      "coverage": "Lance les tests en mesurant la couverture.",
      "typecheck": "Contrôle les types sans rien produire.",
      "lint": "Passe le linter, tout avertissement étant une erreur.",
      "format": "Réécrit le code au format du projet.",
      "verify": "La passe complète avant de livrer : types, lint, format, tests, build, diagnostic.",
      "doctor": "Diagnostique l'application : config, services, ports, dépendances.",
      "doctor:live": "Le même diagnostic, contre l'application qui tourne.",
      "clean": "Supprime le dossier dist.",
      "audit:deps": "Cherche les vulnérabilités connues des dépendances de production.",
      "licenses": "Liste les licences des dépendances.",
      "licenses:write": "Écrit le rapport de licences dans un fichier.",
      "inspect": "Interroge l'application : routes, services, config effective.",
      "ai:sync": "Installe dans le projet les compétences d'agent des paquets présents.",
      "see": "Mesure un écran dans un navigateur piloté — ajouter -- --watch, --audit ou --install.",
      "format:check": "Contrôle le format sans rien réécrire."<% if (it.complete) { %>,
      "infra:up": "Démarre les services d'infrastructure (base, cache) par docker compose.",
      "infra:down": "Arrête et retire ces services."<% } %>
    }
  },
  "dependencies": {
    "nodefony": "^<%= it.nodefonyVersion %>",
    "@nodefony/http": "^<%= it.nodefonyVersion %>",
    "@nodefony/framework": "^<%= it.nodefonyVersion %>",
<% if (it.complete) { %>    "@nodefony/orm-core": "^<%= it.nodefonyVersion %>",
<% if (it.mongo) { %>    "@nodefony/mongoose": "^<%= it.nodefonyVersion %>",
<% } else { %>    "@nodefony/drizzle": "^<%= it.nodefonyVersion %>",
    "drizzle-orm": "<%= it.pkg["drizzle-orm"] %>",
<% } %><% if (it.mongo) { %><% } else if (it.dialect === "postgres") { %>    "pg": "<%= it.pkg["pg"] %>",
<% } else if (it.dialect === "mysql") { %>    "mysql2": "<%= it.pkg["mysql2"] %>",
<% } else { %>    "better-sqlite3": "<%= it.pkg["better-sqlite3"] %>",
<% } %>    "@nodefony/user": "^<%= it.nodefonyVersion %>",
    "@node-rs/argon2": "<%= it.pkg["@node-rs/argon2"] %>",
    "@nodefony/realtime": "^<%= it.nodefonyVersion %>",
    "@nodefony/security": "^<%= it.nodefonyVersion %>",
    "@nodefony/frontend": "^<%= it.nodefonyVersion %>",
    "@nodefony/studio": "^<%= it.nodefonyVersion %>",
    "@nodefony/redis": "^<%= it.nodefonyVersion %>",
<% } else if (it.front) { %>    "@nodefony/frontend": "^<%= it.nodefonyVersion %>",
<% } %><% if (it.front) { for (const [n, v] of Object.entries(it.front.deps)) { %>    "<%= n %>": "<%= v %>",
<% } } %>    "zod": "<%= it.pkg["zod"] %>"
  },
  "devDependencies": {
    "@nodefony/devkit": "^<%= it.nodefonyVersion %>",
    "@types/node": "<%= it.pkg["@types/node"] %>",
<% if (it.mongo) { %>    "mongodb": "<%= it.pkg["mongodb"] %>",
<% } else { %>    "drizzle-kit": "<%= it.pkg["drizzle-kit"] %>",
<% } %>    "@typescript/native-preview": "<%= it.pkg["@typescript/native-preview"] %>",
    "oxlint": "<%= it.pkg["oxlint"] %>",
    "oxlint-tsgolint": "<%= it.pkg["oxlint-tsgolint"] %>",
    "prettier": "<%= it.pkg["prettier"] %>",
    "rolldown": "<%= it.pkg["rolldown"] %>",
<% if (it.front) { for (const [n, v] of Object.entries(it.front.devDeps)) { %>    "<%= n %>": "<%= v %>",
<% } } %>    "typescript": "<%= it.pkg["typescript"] %>",
    "vitest": "<%= it.pkg["vitest"] %>",
    "@vitest/coverage-v8": "<%= it.pkg["@vitest/coverage-v8"] %>"
  },
  "overrides": {
    "@esbuild-kit/core-utils": {
      "esbuild": "<%= it.pkg["esbuild"] %>"
    }
  }
}
