import path from "node:path";
import type {
  IResolvedFrontendEntry,
} from "../interfaces/IFrontBuilder";
import { FrontendPresetUnknownError } from "../src/errors/FrontendError";

/**
 * Génère le contenu d'un `vite.config.generated.mjs` pour le superviseur
 * child_process. Le fichier généré est autosuffisant : il importe Vite +
 * les plugins de chaque preset hardcodés selon les types détectés.
 *
 * Pourquoi pas appeler `IFrontBuilder.buildViteConfig()` directement et
 * passer la config en stdin ? Parce que Vite ne lit pas la config depuis
 * stdin, et que les plugins (instances JS) ne sont pas sérialisables JSON.
 */
export class ViteConfigGenerator {
  /**
   * Construit le content `.mjs` à écrire à côté de `index.html` du module.
   */
  toMjs(
    entries: ReadonlyArray<IResolvedFrontendEntry>,
    mode: "development" | "production",
  ): string {
    if (entries.length === 0) {
      throw new Error("ViteConfigGenerator: empty entries");
    }

    const usedTypes = new Set<string>();
    for (const e of entries) usedTypes.add(e.type);

    const imports: string[] = [`import { defineConfig } from "vite";`];
    const pluginsExprs: string[] = [];
    const optimizeInclude: string[] = [];

    for (const type of usedTypes) {
      switch (type) {
        case "react19":
          imports.push(`import react from "@vitejs/plugin-react";`);
          pluginsExprs.push(`react({ jsxRuntime: "automatic" })`);
          optimizeInclude.push("react", "react-dom", "react-dom/client");
          break;
        case "vanilla":
          // Pas de plugin.
          break;
        default:
          throw new FrontendPresetUnknownError(type);
      }
    }

    const input: Record<string, string> = {};
    for (const e of entries) {
      input[e.entryName] = path.resolve(e.root, e.entryFile);
    }

    const root = entries[0]!.root;
    const outDir = entries[0]!.outDir;

    const inputLines = Object.entries(input)
      .map(([name, file]) => `      ${JSON.stringify(name)}: ${JSON.stringify(file)},`)
      .join("\n");

    const optimizeLines = optimizeInclude
      .map((d) => `    ${JSON.stringify(d)},`)
      .join("\n");

    return `// AUTO-GENERATED by @nodefony/frontend — DO NOT EDIT.
// Regenerated at every dev server start.
${imports.join("\n")}

export default defineConfig({
  mode: ${JSON.stringify(mode)},
  root: ${JSON.stringify(root)},
  plugins: [${pluginsExprs.join(", ")}],
  optimizeDeps: {
    include: [
${optimizeLines}
    ],
  },
  build: {
    outDir: ${JSON.stringify(outDir)},
    manifest: true,
    emptyOutDir: true,
    rollupOptions: {
      input: {
${inputLines}
      },
    },
  },
  server: {
    strictPort: false,
    cors: true,
  },
});
`;
  }
}

export default ViteConfigGenerator;
